services:
  db:
    image: postgres:15-alpine
    container_name: edusense_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Змінено шлях до ініціалізації БД
      - ./infrastructure/postgres_init:/docker-entrypoint-initdb.d
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: iegomez/mosquitto-go-auth
    container_name: edusense_mqtt
    restart: always
    ports:
      - "1883:1883"
    env_file: .env
    volumes:
      # Змінено шлях до конфігів брокера
      - ./infrastructure/mosquitto/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data/
    networks:
      - backend_net

  mqtt_worker:
    build: ./backend
    container_name: edusense_worker
    restart: always
    env_file: .env
    # Змінено команду, оскільки worker.py тепер лежить у папці worker/
    command: python -m worker.worker
    depends_on:
      db:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - backend_net

  backend:
    build: ./backend
    container_name: edusense_backend
    restart: always
    env_file: .env
    environment:
      - LATEST_FW_VERSION=1.0.1
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --workers 2
    volumes:
      # Змінено шлях до папки з прошивками
      - ./edge_devices/builds:/app/firmware
    depends_on:
      db:
        condition: service_healthy
      mosquitto:
        condition: service_started
    networks:
      - backend_net

  frontend:
    build: ./frontend
    container_name: edusense_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend_net
      - backend_net

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  postgres_data:
  mosquitto_data:
