server {
    listen 80;
    server_name localhost;

    # Обробка API запитів
    location /api/ {
        proxy_pass http://backend:5000; # Звертаємось до сервісу за іменем у мережі Docker
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Головна сторінка (заглушка або фронтенд)
    location / {
        add_header Content-Type text/plain;
        return 200 'EduSense Proxy: API is available at /api/schools';
    }
}
